### PR TITLE
Remove 202 response body from LRO patch test

### PR DESCRIPTION
**Pull request by chlowell**
As written, this test expects clients to poll Azure-AsyncOperation after receiving a 202 response with a terminal status. Other similar tests respond with a non-terminal status, which seems reasonable to me, but I instead removed the body to line up with [ARM RPC ](https://github.com/Azure/azure-resource-manager-rpc/blob/master/v1.0/async-api-reference.md#202-accepted-and-location-headers).

### CODE REVIEW

**Review by jhendrixMSFT — APPROVED** [review]

**Comment by jhendrixMSFT** [comment]
@lmazuel any concerns with this?  I suspect it was simply a copy-pasta bug.

**Comment by lmazuel** [comment]
I don't remember this particular test, but some tests are written with broken body on purpose, to be sure runtime are doing the right thing and are prioritizing the right thing to follow.

I think the best question is: why do you need this? :)

**Comment by jhendrixMSFT** [comment]
While I'll defer to @chlowell as he opened the PR, I dug into this a bit, and nothing is really broken.  However, the test is a bit ambiguous.  With the current implementation, the initial response returns a terminal success, so no polling takes place.  With the fix, the 202 with empty body causes polling to happen.  In both cases, the final result is the same.

I do agree with @chlowell that the current implementation violates the ARM RPC spec.  However, if the intent was for the polling runtime to work around that (which might be dubious, but we can save that for later), it would have been ideal for the test to fail if the poller can't cope with a malforms initial response.

**Comment by chlowell** [comment]
That's the gist. A client passes this test only if it polls Azure-AsyncOperation after receiving a terminal response. Is that really the behavior we want? If so, I'm surprised, but this test still seems confused as to its purpose. It doesn't fail when a client prefers Location to Azure-AsyncOperation, for example.

**Pull request closed without merging**
