### PR TITLE
moving from jade to pug since jad has been deprecated

### PR DESCRIPTION
**Pull request by amarzavery**
-  Ran autorest.nodejs tests locally against the new dependency changes and everything worked fine.

```bash
. . .
 ✓ nodejs Swagger ModelFlattening BAT Resource Flattening Operations should put external resource as an array: 2ms
  ✓ nodejs Swagger ModelFlattening BAT Resource Flattening Operations should get external resource as a dictionary: 3ms
  ✓ nodejs Swagger ModelFlattening BAT Resource Flattening Operations should put external resource as a dictionary: 2ms
  ✓ nodejs Swagger ModelFlattening BAT Resource Flattening Operations should get external resource as a complex type: 4ms
  ✓ nodejs Swagger ModelFlattening BAT Resource Flattening Operations should put external resource as a complex type: 2ms
  ✓ nodejs Swagger ModelFlattening BAT Resource Flattening Operations should put simple product to flatten: 3ms
  ✓ nodejs Swagger ModelFlattening BAT Resource Flattening Operations should post simple product with param flattening: 3ms
  ✓ nodejs Swagger ModelFlattening BAT Resource Flattening Operations should put flattened and grouped product: 3ms
    nodejs Swagger BAT coverage report should have 100% coverage: No coverage for scenario: getDateTimeRfc1123MinUtc

No coverage for scenario: expectedNoErrors

No coverage for scenario: expectedPetSadError

No coverage for scenario: expectedPetHungryError

No coverage for scenario: intError

No coverage for scenario: stringError

No coverage for scenario: animalNotFoundError

No coverage for scenario: linkNotFoundError

Passed: 527, Total: 535, coverage: 98% .
  ✓ nodejs Swagger BAT coverage report should have 100% coverage: 4ms

  282 passing (4s)
  1 pending
```

### CODE REVIEW

**Comment by amarzavery** [comment]
@fearthecowboy - Can you please review this PR?

**Comment by fearthecowboy** [comment]
@lmazuel  -- can you test this against Python; we're trying to eliminate some security vulnerability warnings.

**Comment by daschult** [comment]
Looks good to me.

**Comment by lmazuel** [comment]
@fearthecowboy @amarzavery Worked for me on the Python test base :)

**Pull request merged**
