### PR TITLE
fixing lro tests

### PR DESCRIPTION
**Pull request by shahabhijeet**
Updating tests used by LRO.
Added a way to honor Location header in addition to Async-operation header for POST/Delete requests.
The diff shown below is incorrect. All I did was changed few lines and added one additional function.

### CODE REVIEW

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
@amarzavery could you take a quick look in terms of LRO logic? 🙂 I have 0 experience with that....

**Comment by amarzavery** [comment]
Lgtm

**Comment by amarzavery** [comment]
Lgtm

**Comment by amarzavery** [comment]
Lgtm

**Comment by amarzavery** [comment]
Lgtm. Ship it.


Thanks,
Amar Zavery.

________________________________

**Pull request merged**
