### PR TITLE
Fix date comparison to allow ISO 8601 format

### PR DESCRIPTION
**Pull request by pakrym**
Current version doesn't allow `0001-01-01T10:00:00.000Z`

### CODE REVIEW

**Comment by pakrym** [comment]
or fix whoever sends `0001-01-01T10:00:00Z`

**Comment by lmazuel** [comment]
@pakrym actually hold on, why do we need any kind of string test at all? Why `new Date(req.body).toString() === new Date('0001-01-01T00:00:00+14:00').toString()` is not enough here?

**Comment by pakrym** [comment]
I think the part you quoted is just plain wrong:

```
new Date("0001-01-01T10:00:00.000Z").toISOString()
"0001-01-01T10:00:00.000Z"

new Date("0001-01-01T10:00:00.000Z").toString()
"Mon Jan 01 0001 02:07:02 GMT-0752 (Pacific Standard Time)"

new Date("0001-01-01T00:00:00+14:00").toString()

"Sun Dec 31 0000 02:07:02 GMT-0752 (Pacific Standard Time)"
new Date("0001-01-01T00:00:00+14:00").toISOString()
"0000-12-31T10:00:00.000Z"
```

**Comment by lmazuel** [comment]
@pakrym not sure I follow you, the idea is to check that *semantically* the two dates are the same. How you received them as string doesn't matter, as long as they represent the same point in time.

**Comment by pakrym** [comment]
What I'm trying to say is that two values the test is currently checking do not represent the same point in time.

**Comment by lmazuel** [comment]
@pakrym got it, let's a do a more massivce clean-up, that should be the same point in time. It seems someone at some point updated the tests to it can pass without thinking it through :p

**Comment by pakrym** [comment]
I'll merge this for now so we can get the test re-enabled.

**Pull request merged**
