### PR TITLE
Added new swagger and route for missing discriminator scenario

### PR DESCRIPTION
**Pull request by williexu**
new coverage test for missing discriminators while serializing and deserializing

### CODE REVIEW

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
@williexu @amarzavery Am I missing what this test is doing? It's called "missing discriminator", but the `regularSalmon` used by the added route has `fishtype` on all levels, doesn't it?

The again, a test for missing discriminator can really only send something with missing discriminator, but we can't expect clients to send something without discriminator. So shouldn't the test, say, return something without discriminator but then expect it to be passed back in (and set to the statically declared type)?

**Comment by amarzavery** [comment]
@olydis - This test ensures that if someone does not deliberately provide the discriminator property (for some reason, it is possible for node sdk since people provide json objects, for strongly typed languages, the Object that you create has the discriminator set as constant, hence it will always be present) then the runtime should not throw but auto populate the value for discriminator property based on the reference to the model in the swagger (usually the parent or intermediate parent) rather than throwing an error that discriminator property was not found.

At the same time we wanted to make sure that when the server sends an object without the discriminator property, the runtime should auto populate the value for discriminator property based on the reference in the swagger (usually the parent or intermediate parent).

So the serialization test is correct. We need to send a modified regular salmon which will not have the top level fishtype property and we shall send a PR to fix that.

Does that make sense?

**Comment by amarzavery** [comment]
The new version 2.3.20 fixes it.

**Pull request merged**
